### ISSUE TITLE
Crash on multiple !play requests

### ISSUE THREAD

**Issue by Buluphont** [Buluphont/CalicoChan#17]
Decent odds this can be solved by queueing up queue additions and serially resolving them.

**Comment by Maldaris** [comment]
https://www.npmjs.com/package/node-mutex

```
mutex.lock('music-enqueue', function(err, unlock){ queue_tune(); unlock(); });
```

Possible solution?

**Comment by Buluphont** [comment]
Looks like just what we need.

**Comment by Buluphont** [comment]
Even has a promisifed version. 💯

**Comment by Maldaris** [comment]
worth noting that a `redis` server is required for this module.

**Comment by Buluphont** [comment]
I see. It's designed for use across multiple instances.

Perhaps a bit too heavy for what I need; a simple Promise array should suffice, then.

**Comment by Buluphont** [comment]
Nuked tunes altogether ages ago.
