### ISSUE TITLE
Random Adversary Function

### ISSUE THREAD

**Issue by GardEvelyn** [Buluphont/CalicoChan#18]
To aid people with trying out new adversaries they haven't looked at before. It could possibly throw out the same text that !oracle/spoiler [Adversary] does.

**Comment by Buluphont** [comment]
After discussion, we have decided on the initial implementation:

`randomadv [setcode]`

Pulls a random Adversary from the Adversary DB from the specified set, if present. From all sets, otherwise.

**Comment by Buluphont** [comment]
Implemented by #19
