### ISSUE TITLE
Tweak Random Abilities

### ISSUE THREAD

**Issue by Buluphont** [Buluphont/CalicoChan#39]
Please leave feedback here. The relevant file:
https://github.com/Buluphont/CalicoChan/blob/master/assets/json/adversary_abilities.json

**Comment by Rediblackdragon** [comment]
I'd say to get rid of a lot of the "bomb" abilities, such as Phyrexia or Purist. Also don't just pull abilities from pre-existing Adversaries. (can Myra be in this because it's limited anyways?)

**Comment by Buluphont** [comment]
Task rejected: Random abilities removed from League
