### ISSUE TITLE
Make it so that league collections can be retrieved in a way that Cockatrice can use as a set?

### ISSUE THREAD

**Issue by GardEvelyn** [Buluphont/CalicoChan#40]
Having the league collection as its own set means people can search, filter, and understand their collection in Cockatrice more easily. Issues with this would be that it could be a much bigger strain on Calico to not just fetch random card names, but to fetch all of its oracle text too, and then to put them in an xml to be used as a set.

**Comment by Buluphont** [comment]
Implemented. `collection get xml`
